import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/connexion.module.css'

export default function Connexion() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Final project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar">
        <div className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          <span>RIDE</span>
        </div>
        <div></div>
        {/* COMPONENT */}
        <button className="button">Connexion admin</button>
      </nav>

      <div className={styles.formDiv}>
        <span>Retour</span>
        <form action="">
          <p>Connexion</p>
          <input type="text" placeholder='Identifiant' />
          <input type="password" placeholder='Mot de passe' />
          <button className="button">Connexion</button>
        </form>
      </div>

      <footer className='footer'>
        <ul>
          <li>Contact</li>
          <li>Conditions généralespdf</li>
        </ul>
        <p className={styles.footerP}>RIDE 2022 - tout droits reservés</p>
      </footer>

    </div>
  )
}
