import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Final project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.navbar}>
        <div>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          <span>RIDE</span>
        </div>
        <div></div>
        {/* COMPONENT */}
        <button className={styles.button}>Connexion admin</button>
      </nav>
      <div className={styles.headerImg}></div>
      <div className={styles.formDivContainer}>
        <div className={styles.formDiv}>
          <p>▷ Depuis 2008, RIDE, agence de location de voitures de luxe propose ses services partout en France (Paris, Monaco, Nice, Cannes, Saint-Tropez, Courchevel, Saint-Moritz...).Notre expérience est à votre service pour répondre à toutes vos demandes</p>
          <hr />
          <span className={styles.formDivSpan}>Inscription</span>
          <p>Je suis :</p>
          <div>
            {/* COMPONENT */}
            <div className={styles.formDivRadiosDiv}>
              <input type="radio" />
              <span>une entreprise</span>
            </div>
            {/* COMPONENT */}
            <div className={styles.formDivRadiosDiv}>
              <input type="radio" />
              <span>un particulier</span>
            </div>
          </div>
          <div className={styles.formDivInputsDiv}>
            <input type="text" className={styles.formDivInputs} placeholder="Nom" />
            <input type="text" className={styles.formDivInputs} placeholder="Prénom" />
            <input type="text" className={styles.formDivInputs} placeholder="E-mail" />
            <input type="text" className={styles.formDivInputs} placeholder="Numéro de téléphone" />
            <select className={styles.formDivInputs} placeholder="">
              <option value="">aa</option>
              <option value="">aa</option>
            </select>
          </div>
          <div>
            <input type="checkbox" />
            <span>j’atteste que je possède un permis de conduire valide.</span>
          </div>
          {/* COMPONENT */}
          <button className={styles.button}>Demander mon inscription</button>
        </div>
      </div>

      <footer className={styles.footer}>
        <ul>
          <li>Contact</li>
          <li>Conditions généralespdf</li>
        </ul>
        <p className={styles.footerP}>RIDE 2022 - tout droits reservés</p>
      </footer>

    </div>
  )
}
